export const POST_LOGIN_REQ="POST_LOGIN_REQ";
export const POST_LOGIN_SUCCESS="POST_LOGIN_SUCCESS";
export const POST_LOGIN_FAILURE="POST_LOGIN_FAILURE";

export const POST_LOGOUT_REQ="POST_LOGOUT_REQ";
export const POST_LOGOUT_SUCCESS="POST_LOGOUT_SUCCESS";
export const POST_LOGOUT_FAILURE="POST_LOGOUT_FAILURE";

export const SAVE_USER_DATA="SAVE_USER_DATA"
export const DELETE_USER_DATA="DELETE_USER_DATA"